### ISSUE TITLE
[react-ga] with trackers: undefined

### ISSUE THREAD

**Issue by muscaiu** [react-ga/react-ga#179]
```
ReactGA.initialize('xxxx-yyy', { debug: true });

  addEvent() {
    ReactGA.event({
      category: 'event2',
      action: 'action2',
      label: 'label2'
    })
  }
```

>[react-ga] with trackers: undefined
Why is this log returning `undefined`?

**Comment by KingstonDuo** [comment]
We are also getting this error and events aren't being sent to Google Analytics. Downgrading to 2.2.0 fixes the problem. Thanks!

**Comment by bertrand-riviere** [comment]
Hi,
I do have the same issue.. And event are indeed no longer sent to GA.

**Comment by jaschaio** [comment]
I am having a similar issue. The package is just not working with me in the latest version (2.3.5). I have initalized it with debug on and nothings is being echoed in the console. Downgrading to 2.0.0 helped.

**Comment by SimeonC** [comment]
The undefined is because of the optional parameter, it's not an error you have to be worried about.
I did some experimenting and it looks like Using "Full Mode" under Admin > Property Settings seems to fix it. Googling on why this fixes it is extremely unproductive as I'd like to know why one works and the other doesn't but no luck here - I've also no idea why this would need to change just because we moved the code around.
![image](https://user-images.githubusercontent.com/1085899/32403988-1231292c-c18a-11e7-82d7-967067fd3160.png)

It's not the solution I'd like to give but I can't seem to figure out what is actually causing it - maybe the new `gtag.js` would fix this but also maybe not.

**Comment by SimeonC** [comment]
The only other potential fix I can do for this is in this PR. If you have the time clone it, run `npm start` and test the events page in the demo using your GA ID (localhost:8080).

**Comment by justinkahrs** [comment]
I ran across this issue myself, and it was solved with flipping the analytics to Full view mode. Thanks @SimeonC

**Comment by rlreamy** [comment]
What is the status on this?  The workaround seems like it is leaving a lot of people unsatisfied, though it appears to work.

**Comment by rachelruderman** [comment]
Also interested in a status update on this

**Comment by SimeonC** [comment]
Last time I looked I couldn't figure out why Full view mode is required.
No-one is actively working on this as it's probably a really hard problem to fix and though we have a couple of maintainers this is a project we maintain in our spare time. Anyone has more information/potential fixes/has time to fix it would be a big help.

**Comment by odedvisiblerisk** [comment]
still happen to me in version 3.3 also after updating to full view :( 
![image](https://user-images.githubusercontent.com/78471988/114070111-59981980-98a8-11eb-81fc-18f543f522cc.png)

**Comment by ermiaSparkle** [comment]
> still happen to me in version 3.3 also after updating to full view :(
> ![image](https://user-images.githubusercontent.com/78471988/114070111-59981980-98a8-11eb-81fc-18f543f522cc.png)

@SimeonC
